### ISSUE TITLE
Image Translation is automatically turned off

### ISSUE THREAD

**Issue by npivic** [muckmuck96/obsidian-md-to-jira#1]
In the Obsidian settings, I found this:

<img width="713" alt="image" src="https://user-images.githubusercontent.com/90442219/211776905-6dcbac5c-cd36-4659-901b-0b357e06aa1d.png">

I enable this setting, but when I select another plugin and return, the switch is disabled. Weird!

The same behaviour repeats when I use the plugin in the Obsidian Sandbox vault, which makes me believe this is not an issue that happens because of a dodgy vault…

Thanks for making this plugin!

**Comment by muckmuck96** [comment]
This is actually a feature that should come with the next update. Why the setting option is already in version 0.0.2 is a bit of a mystery to me, something must have gone wrong in the deployment.
However, I am still working on the function and will release it with the next version.

**Comment by muckmuck96** [comment]
I will publish a small update soon, in which a notification will be added to the images, that they have to be transferred manually additionally.

**Comment by muckmuck96** [comment]
I will close this ticket for now as the update has disabled this feature for now.
