### ISSUE TITLE
List levels are not correctly mapped to Jira markdown

### ISSUE THREAD

**Issue by BartoszCiesla** [muckmuck96/obsidian-md-to-jira#3]
Following list in Obsidian
```
- top level 1
	- sub item 1
	- sub item 2
- top level 2
	- sub item 3
```
is translated into
```
-- top level 1
- sub item 1
- sub item 2
- top level 2
- sub item 3
```
which is not correct. It should  be something like
```
- top level 1
-- sub item 1
-- sub item 2
- top level 2
-- sub item 3
```

I'm using latest version of the plugin (0.0.3) and Obsidian v1.4.14

**Comment by muckmuck96** [comment]
I took a look at the relevant post and agree with you, I will make appropriate adjustments there and bring forward a smaller update.

**Comment by muckmuck96** [comment]
I'm glad to hear that, I'll update soon so that callouts can be transferred as well.

**Comment by muckmuck96** [comment]
The latest version now fixes the bug and support callouts too. 👍

**Comment by BartoszCiesla** [comment]
Thanks for fixing but after upgrade to 0.1.0 I'm having different kind of problem - when I try to migrate note to Jira format I get only last line - for example for:

```
- top level 1
	- sub item 1
	- sub item 2
- top level 2
	- sub item 3

#tag #other 
```

note conversion gives me only this:
```
h1.tag #other 
```

Same for the selection - only last line is being copied

**Comment by muckmuck96** [comment]
Thank you for this report. I directly fixed it and published a hotfix for it.
