### ISSUE TITLE
When converting an external link, it still adds a message that manual copying is required

### ISSUE THREAD

**Issue by 42ama** [muckmuck96/obsidian-md-to-jira#5]
When converting an external link, it still adds a message that manual copying is required

**Steps for reproduction:**
1. Insert the following text into Obsidian:
- Test [link](https://github.com/)
2. Convert the text to Jira format using a plugin
**Expected**: The text became "Test [link|https://github.com/]".
**Actual**: The text became:
```
Test {panel:borderColor=#ffecb5|bgColor=#fff3cd}
				{color:#664d03}+*Warning:*+ The following file must be transferred manually via drag & drop: *link*{color}
				{panel}
				
				[link|https://github.com/]
```

This behavior is understandable for links to files internal to Obsidian (framed in double square brackets), but it should not be for external links.

**Comment by muckmuck96** [comment]
Thank you for reporting this issue. I will investigate the behavior and work on a fix as soon as possible.

**Comment by muckmuck96** [comment]
The bug has been fixed in the new version, which includes a converter that offers improved support. If you're not satisfied with the beta state of the new converter, you can switch back to the legacy converter at any time via the settings.
