### ISSUE TITLE
New converter removes line breaks

### ISSUE THREAD

**Issue by itsbreaded** [muckmuck96/obsidian-md-to-jira#6]
The new converter removes line breaks from any content that is copied. 
- Copy Selection & Note both affected

**Steps to reproduce**
1. Copy any text that has line breaks
2. Paste it somewhere

See:

https://github.com/user-attachments/assets/f7c67583-3601-489f-a8a9-3da28519196f

**Comment by muckmuck96** [comment]
Thank you for your bug report. My test file has line breaks as well, so I cannot really reproduce this issue. Could you please send me the content of your test file? I will check it there and try to fix it as soon as possible.

**Comment by itsbreaded** [comment]
@muckmuck96, here's the file: [Line break file.md](https://github.com/user-attachments/files/16717288/Line.break.file.md)

I tested without other plugins and get the same results. I'm on Windows 11 with Obsidian 1.6.7 and using plugin version 0.2.0

**Comment by muckmuck96** [comment]
I reviewed the file you provided, identified the issue, and implemented a quick fix. Thank you for reporting this.
